export const styles = {
  address: {
    bgcolor: "#2c2c2c",
    color: "white",
    px: 3,
    py: 1.5,
    borderRadius: "16px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    fontWeight: 500,
    textAlign: "center",
    fontSize: "16px",
    maxWidth: "200px",
    mb: 1.5,
    position: "relative",
    "&::after": {
      content: '""',
      position: "absolute",
      bottom: -8,
      left: "50%",
      transform: "translateX(-50%)",
      width: 0,
      height: 0,
      borderLeft: "8px solid transparent",
      borderRight: "8px solid transparent",
      borderTop: "8px solid #2c2c2c",
    },
  },
  marker: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -100%)",
    zIndex: 999,
    pointerEvents: "none",
  },
  mapContainer: { height: "500px", width: "100%", position: "relative" },

  nearMe: {
    position: "absolute",
    bottom: 70,
    right: 16,
    zIndex: 1000,
    backgroundColor: "white",
    boxShadow: 2,
    "&:hover": {
      backgroundColor: "#f0f0f0",
    },
  },

  markerAnimation: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -100%)", // по центру и вверх
    zIndex: 1000,
    pointerEvents: "none",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
};
